#######################
# Configuration du thème
#######################
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
after_footer_scripts: []

#######################
# Configuration du site
#######################
locale: "fr-FR"
title: "La pensine"
title_separator: "|"
subtitle: "Docs et articles techniques que je partage..."
name: "Dimitri Froidure"
description: "Linux System Administration, Security, and DevOps"
url: "https://blog.froidure.net"
repository: "dfroidure/blog.froidure.net"
words_per_minute: 160
breadcrumbs: true
masthead_title: "La pensine"

#######################
# Profil auteur
#######################
author:
  name: "Dimitri Froidure"
  avatar: "https://avatars.githubusercontent.com/u/190739018"
  bio: "Linux System Administrator & Security Enthusiast"
  location: "In a Shell somewhere..."
  links:
    - label: "Blog"
      icon: "fas fa-fw fa-link"
      url: "https://blog.froidure.net"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/dimitri-froidure"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dfroidure"

#######################
# Navigation et liens
#######################
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/dimitri-froidure"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dfroidure"

#######################
# Fonctionnalités
#######################
search: true
atom_feed:
  hide: true
date_format: "%d-%m-%Y"
share: false

#######################
# Collections et archives
#######################
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

#######################
# Plugins
#######################
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

#######################
# Defaults
#######################
defaults:
  # Configuration des posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
      show_date: true
      sidebar:
        nav: # vide pour supprimer la sidebar

  # Configuration des pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

#######################
# Gestion des fichiers
#######################
include:
  - .htaccess
  - _pages

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp